# Generated by Django 4.1.3 on 2023-01-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
