# Generated by Django 4.1.2 on 2022-11-03 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscription',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
