# Generated by Django 4.1.2 on 2022-11-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscription'),
    ]

    operations = [
    ]
