# Generated by Django 4.1.2 on 2022-11-03 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_merge_20221103_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscription',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
