# Generated by Django 4.1.3 on 2022-12-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='subscription',
            new_name='subscribers',
        ),
    ]
