# Generated by Django 4.1.2 on 2022-10-30 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
